#!/usr/bin/env node

// Avoid conflicts with another version
if(typeof require('module')._extensions['.coffee']==='undefined'){
  require('coffee-script/register');
}

var jasminetea= new (require('./lib'));

if(module.parent===null){
  // Fix exception of CLI
  process.on('uncaughtException',function(error){
    throw error;
    process.exit(1);
  });

  jasminetea.cli(process.argv.slice(2));
}

module.exports= jasminetea;